### ISSUE TITLE
Create a patch on WordPress trac from local diff

### ISSUE THREAD

**Issue by ericandrewlewis** [aaronjorbin/grunt-patch-wordpress#30]
I have a hunk of code @helenhousandi gifted me a long time ago that creates a patch on WordPress trac based on a local diff.

I'd like to see if we can port that functionality in here. Into it?

**Comment by aaronjorbin** [comment]
Absolutely!  I am 100% for this.

**Comment by helenhousandi** [comment]
Just a note that I don't think you could really port over how that works specifically, as it reaches into Keychain for your .org password and then connects over XML-RPC, which is restricted to certain users. But the feature itself would be great :)

**Comment by aaronjorbin** [comment]
We will need a secure cross platform way of storing the password. 

At one time, @nacin had suggested we could open up the XML-RPC endpoint for patch uploads for more/all users.

**Comment by ericandrewlewis** [comment]
> @nacin had suggested we could open up the XML-RPC endpoint for patch uploads for more/all users

It would be nice to look into this before implementing this feature. I've opened [#1500](https://meta.trac.wordpress.org/ticket/1500) on Meta Trac to discuss.

**Comment by nacin** [comment]
Assume we can open it up to everyone. I'll take care of it. Go forth and implement!

**Comment by ntwb** [comment]
This can be closed, merged in from #32 https://github.com/aaronjorbin/grunt-patch-wordpress/commit/e1ffac901ad4ddcd491063f695adc82bf6674f2e

**Comment by aaronjorbin** [comment]
@nacin It's ready to be opened up to everyone. 

Closing this as fixed as the code is there and it's released
