### ISSUE TITLE
Allow patches from Github

### ISSUE THREAD

**Issue by ellatrix** [aaronjorbin/grunt-patch-wordpress#93]
Recently I've been using Github a lot to create patches to run the tests. Unfortunately, the `grunt patch:#` command doesn't work together with this workflow. Would be awesome if it could! :)

**Comment by TimothyBJacobs** [comment]
I think this might be a dupe of #83. If you didn't know, you can also do `grunt patch:https://github.com/WordPress/wordpress-develop/pull/421` which will apply the linked PR.

**Comment by ellatrix** [comment]
Oh nice! I think something else is wrong with my setup. Getting this when there is an attachment as well.

```
>> getPatchFromTicket fail 
>>  status: 403
```
